pref("extensions.zotero-copilot.provider", "gemini");
pref("extensions.zotero-copilot.apiKey", "");
pref("extensions.zotero-copilot.geminiApiKey", "");
pref("extensions.zotero-copilot.model", "claude-opus-4-7");
pref("extensions.zotero-copilot.geminiModel", "gemini-2.5-flash");
pref("extensions.zotero-copilot.maxTokens", 4096);
pref("extensions.zotero-copilot.systemPrompt", "You are an expert research assistant helping the user understand academic papers. Answer based only on the provided paper context. When citing, reference page numbers if available.");
pref("extensions.zotero-copilot.allowFullTextUpload", false);
pref("extensions.zotero-copilot.temperature", 0.3);
pref("extensions.zotero-copilot.sidebarCollapsed", false);
pref("extensions.zotero-copilot.mcpEnabled", false);
pref("extensions.zotero-copilot.mcpPort", 23119);
pref("extensions.zotero-copilot.mcpAllowWrite", false);
